repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: ^(.github/workflows/)
      # - id: check-added-large-files
      - id: trailing-whitespace
      # - id: end-of-file-fixer
      - id: check-json
      - id: no-commit-to-branch
        args: ["--branch", "main"]

  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        args: ["--line-length=192"]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: ["--max-line-length=192", "--ignore=E501,E401,F84,W503,E722,E203"]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
