services:
  api:
    build: ./app
    restart: always
    command: uvicorn main:app --reload --workers 1 --host 0.0.0.0 --port 8005
    volumes:
      - ./app/:/opt/projects/app/
      - ./logs/:/opt/projects/app/logs
    ports:
      - "8005:8005"
    env_file:
      - ./.env/dev.env
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -f http://localhost:8005/v1/health/ping || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 3
    depends_on:
      - db

  db:
    image: mongo
    restart: always
    volumes:
      - ./database:/data/db
    command: --quiet
    ports:
      - 27019:27017
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --quiet | grep 1
      interval: 60s
      timeout: 60s
      retries: 6