services:
  api-test:
    build: ./app
    restart: always
    command: pytest .
    ports:
      - "8005:8005"
    env_file:
      - ./.env/dev.env
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -f http://localhost:8005/v1/health/ping || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 3
    depends_on:
      - db-test

  db-test:
    image: mongo
    restart: always
    command: --quiet
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --quiet | grep 1
      interval: 60s
      timeout: 60s
      retries: 6