services:
  api-test:
    build:
      context: ./app
      dockerfile: Dockerfile.test
    restart: always
    command: pytest ./tests/
    volumes:
      - ./tests/:/opt/projects/app/tests
    env_file:
      - ./.env/dev.env
      - ./.env/test.env
    healthcheck:
      test: ["CMD", "sh", "-c", "curl -s -f http://localhost:8001/v1/health/ping || exit 1"]
      interval: 60s
      timeout: 3s
      retries: 3
    depends_on:
      - db-test

  db-test:
    image: mongo
    restart: always
    command: --quiet
    healthcheck:
      test: echo 'db.runCommand({serverStatus:1}).ok' | mongosh admin --quiet | grep 1
      interval: 60s
      timeout: 60s
      retries: 6